# Generated by Django 5.2.5 on 2025-08-25 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_datecompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='descripción',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='datecompleted',
            new_name='fechacompletado',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='important',
            new_name='importante',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='titulo',
        ),
    ]
